### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by mairm1340** [sjhloco/firewall_policy_report#2]
Hi
This did work for me but how do we add option for enable password
and also by any chance we can ask for user input for username/password/enable password

**Comment by sjhloco** [comment]
> how do we add option for enable password

It uses [Netmiko](https://ktbyers.github.io/netmiko/docs/netmiko/cisco/cisco_asa_ssh.html) to connect, from what I understand this automatically puts it in enable mode. 

> any chance we can ask for user input for username/password/enable password

No this is by design so I can run again a multitude of devices easily. I may change these to env_vars at some point but I dont envisage adding a prompt for username and password as is only really good if running against single devices
